### ISSUE TITLE
Issues with Jumping Night version 2.1.77

### ISSUE THREAD

**Issue by Tala** [N-Bz/bybop#1]
Hey, 
first: thanks for this great project I really like to play round with it and got it running for a gesture control of the jumping night using Microsoft Kinect. 
Unfortunately, I didn't get the drone running with the current SDK and firmware version 2.1.77.
After connecting to the drone and starting the interactive skript, I get no response. The drone can not be found. 
Do you have any clue why it isn't working and how to fix it?
best regards,
Tala

**Comment by Tala** [comment]
The problem I was reporting was fixed by using netifaces 0.10.4 instead of 0.10.5. To make the project work with the current SDK version running (on Windows) I had to make some changes:
* Copy xml Files from \packages\arsdk-xml\xml to \packages\libARCommands\Xml
* change ARCommandsParser Line 719 to "XMLFILENAME_PREFIX=os.path.join(pathToARCommands, 'Xml','')"
* rename ardrone3, common, jpsumo, minidrone, powerup, skyctrl to *_commands.xml
* rename jpsumo_commands.xml to JumpingSumo_commands.xml
* uncomment lines 35-41 in bybop_Commands.py

hope this helps

**Comment by N-Bz** [comment]
I updated the code to use the "new" arsdk-xml repository (xmls & parsers) instead of the legacy one.

The new code should work exactly as before, except that the projects names have changes ('JumpingSumo' is now 'jpsumo', like you've seen)

Let me know if you still have issues.
