### ISSUE TITLE
PilotingState SpeedChanged is absent in drone state for Jumping Sumo

### ISSUE THREAD

**Issue by LiudmylaN** [N-Bz/bybop#10]
When I try to retrieve the device state to find out its speed, there is no SpeedChanged command for PilotingState class. The command is specified in arsdk-xml though:

`<cmd name="SpeedChanged" id="2">
	Notification sent when JS speed changes.
	<arg name="speed" type="i8">
		Speed command applied to motors in range [-100;100].
	</arg>
	<arg name="realSpeed" type="i16">
		Actual real-world speed in cm/s. Value -32768 returned if not available.
	</arg>
</cmd>`

and screen shot shows what I am actually getting.
![screen shot 2017-10-20 at 15 42 09](https://user-images.githubusercontent.com/3001889/31824088-50aa8532-b5ae-11e7-9267-b069fd87f3a1.png)

Is it a firmware problem? How can I check this?

Thank you

**Comment by N-Bz** [comment]
Hi,

This project has its own version of  `arsdk-xml` as a submodule. I've just made a commit which update it to the latest public revision.

You can always do it manually by running `git submodule update --remote`.

**Comment by LiudmylaN** [comment]
Hi. Thank you. It does not change things for me. I used a recent version from remote source.

It looks more like SpeedChanged is not retrieved from the device. I didn't find out yet how to check it.

**Comment by N-Bz** [comment]
If I remember correctly, this command is only sent by Jumping Race drones, not by Jumping Sumo / Jumping Night drones ... That may be the reason too ;)

**Comment by LiudmylaN** [comment]
This command is specified in jsumo.xml. I think jumping race and sumo share the same specification. I can send the command to set the speed, and move the drone around. It make no sense not to have the state for speed if I can change it.

**Comment by N-Bz** [comment]
I just confirmed with the firmware team: this command is indeed "Jumping Race" only.

I don't know the exact reason behind that choice (that's more a question for the support forums, but to be honest there is a very little chance that this would be implemented), but that's why you never receive the message.

**Comment by LiudmylaN** [comment]
Thank you very much for your help!
