### ISSUE TITLE
Trouble with running

### ISSUE THREAD

**Issue by jesmitty** [N-Bz/bybop#13]
In the bybop readme, it says: "This project contains a sample code (samples/interactive.py), which uses `bybop` to find a drone, and to connect to it, then pops an interactive python shell in which you can play with the drone object. You can run this sample with the following command (run inside the samples directory):
`ARSDK_PATH=/path/to/the/ARSDK ./interactive.py`
Where `ARSDK_PATH` is the path to the folder containing the `ARSDKBuildUtils` and the `libARCommands` repo (see Prerequisites)."

I am finding this a little confusing. If I run interactive.py from F:\Bebop2\bybop\samples directory and have F:\Bebop2\ARSDKBuildUtils and F:\Bebop2\libARDiscovery directories. What do I set ARSDK to?

I set ARDSK_PATH = F:\Bebop2\ARSDKBuildUtils; F:\Bebop2\libARDiscovery and get this error:
python MyInteractive.py
Traceback (most recent call last):
  File "MyInteractive.py", line 19, in <module>
    import Bybop_Device
  File "../src\Bybop_Device.py", line 10, in <module>
    from Bybop_Commands import *
  File "../src\Bybop_Commands.py", line 29, in <module>
    from ARCommandsParser import *
ModuleNotFoundError: No module named 'ARCommandsParser'

I suspect I did not set ARSDK_PATH correctly. Do you know what I am missing?

**Comment by N-Bz** [comment]
You're quoting a pretty old readme here, I did a major update in march 2017 which removed the necessity of the ARSDK_PATH environment variable.

Could you try to update your code and see if you still have an issue ?

**Comment by jesmitty** [comment]
Also, I can explicitly put where to find parser in python code with:
  sys.path.insert(0, 'F:/Bebop2/ARSDKBuildUtils/Utils/Python')

but I'll still get:
File "F:/Bebop2/ARSDKBuildUtils/Utils/Python\ARCommandsParser.py", line 725, in parseAllProjects
    listDir = os.listdir(XMLFILENAME_PREFIX)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\Bebop2\\ARSDKBuildUtils\\Utils\\Python\\libARCommands/Xml/'

**Comment by jesmitty** [comment]
I am sorry. I didn't read your comment. I did a git update from https://github.com/Parrot-Developers/bybop and git tells me I am up to date. Is there a different repo?

**Comment by N-Bz** [comment]
Maybe this one.

The Parrot-Developers fork is not up to date, this one is the main development repo I keep up to date

**Comment by jesmitty** [comment]
Thanks for quick update. There are 2 repos. When I use this one I do get a different error, viz:

(C:\anaconda3) F:\Bebop2\bybop-master\samples>python interactive.py
Traceback (most recent call last):
  File "interactive.py", line 13, in <module>
    import Bybop_Device
  File "../src\Bybop_Device.py", line 10, in <module>
    from Bybop_Commands import *
  File "../src\Bybop_Commands.py", line 11, in <module>
    import arsdkparser
ModuleNotFoundError: No module named 'arsdkparser'

Do I have to set some env variable that I am missing?

**Comment by N-Bz** [comment]
Did you apply the instructions in the "new" readme ? (i.e. "After cloning this repo, you must initialize & update the submodules: git submodule init; git submodule update")

**Comment by jesmitty** [comment]
Thanks. My mistake. I can get this to run. It gets as far as "searching devices". I have a bebop 2 on. Have PC connected to bebop wifi.  I can debug from here. Thanks for all your timely help.
