### ISSUE TITLE
ARCommands XML is not found in my package.

### ISSUE THREAD

**Issue by wsywade** [N-Bz/bybop#2]
I couldn't find the ARCommands XML in the package/ARCommands/. How to deal with this problem?
THX!

**Comment by wsywade** [comment]
@N-Bz

**Comment by N-Bz** [comment]
The commands xmls are now located in the [arsdk-xml](https://github.com/Parrot-Developers/arsdk-xml) repo, which is included as a submodule.

You should be able to get it by updating bybop and following the installation instructions.
