### ISSUE TITLE
Issue about the zeroconf.

### ISSUE THREAD

**Issue by wsywade** [N-Bz/bybop#3]
@N-Bz 
Thanks for your help before! Our project is based on the Window platform, so I try to execute the bybop on Windows. However, the get_device() function couldn't found the device in the Wi-Fi connection. Why?
I'm curious about the zeroconf that how it find the device and change the value in self._services. I couldn't get the point in the source code. I search on the Internet for the zeroconf in Python but found nothing. Could you give me some instruction or tutorial about zeroconf?
THX!

**Comment by N-Bz** [comment]
Hi,

You can find [here](https://pypi.python.org/pypi/zeroconf) all the informations about the zeroconf library I use for this project.

I did not test the project on windows (actually I only tested it on my Ubuntu 14.04 workstation), but I'm pretty sure that porting bybop to windows should be pretty straightforward (if not already OK)

Nicolas.

**Comment by Tala** [comment]
@wsywade There is a problem with the current version of zeroconf on windows. Uninstall netifaces 0.10.5 and reinstall 0.10.4 instead. That should fix the problem.

**Comment by wsywade** [comment]
@Tala Thanks for your answer! I install the netifaces 0.10.5 and it works on Windows OS well now. 


Shiyu
