### ISSUE TITLE
How to solve it  "ImportError: No module named readline"

### ISSUE THREAD

**Issue by hsy77101** [N-Bz/bybop#5]
I tried to run interactive.py on python 2.7.
But it had some of error like following.
I finished clone and update "git submodule init; git submodule update"
Please let me know how to solve it.

Thank you.

**>>> ================================ RESTART ================================
>>> 

Traceback (most recent call last):
  File "D:\ParrotDroneSDK\Python\ParrotPythonSDK\bybop\samples\interactive.py", line 7, in <module>
    import readline
ImportError: No module named readline
>>>**

**Comment by N-Bz** [comment]
I guess you're on windows, and windows does not seem to have the readline module available.

As this module is only required for code completion in the interactive console of the sample, you can remove the lines 7, 8, 47 and 48 of the `interactive.py` sample (i.e all the lines referring to `readline` or `rlcompleter`)

Anyways, I have to say that I did never actually (and don't plan to) test this project on windows, so I can't really help more if it breaks in the internals.

**Comment by Tala** [comment]
Hey @hsy77101 
I'm not sure if the change is done by me or is already there, but on windows machines you can simply use pyreadline instead of readline and it works fine.

@N-Bz : If you want you could ping me on windows related problems, I got it set up and running on windows 8 and 10 :) 
I'm happy to help

**Comment by hsy77101** [comment]
I tried to pyreadline instead of readline. But it was same error.
I use windows7 with python 2.7.12.
Do I need to modify interactive.py more?
Please check the following procedure I did.

1. I just run Python GUI.
2. File>Open..>interative.py
3. Run>Run Module
But I got error.

**Comment by hsy77101** [comment]
After removing the lines 7, 8, 47 and 48 of the interactive.py sample, I got following errors.

Traceback (most recent call last):
  File "C:\Python27\bybop\samples\interactive.py", line 12, in <module>
    from Bybop_Discovery import *
  File "../src\Bybop_Discovery.py", line 3, in <module>
    from zeroconf import ServiceBrowser, Zeroconf
ImportError: No module named zeroconf

**Comment by Tala** [comment]
Have you installed the Zeroconf and pyreadline packages? If so, in which version?

**Comment by hsy77101** [comment]
I just installed python 2.7.12 on  windows7.
And then After cloning this repo, I initialized & updated the submodules: git submodule init; git submodule update
That's all I did.

**Comment by Tala** [comment]
The error message "No module named XY found" says that the package is missing on your system.

You have to install the required packages like pyreadline and zeroconf (e.g. by using pip). Be aware that there may be a bug in the current zeroconf package (see https://github.com/N-Bz/bybop/issues/3).

**Comment by asoccer** [comment]
Try to stick with 32bit edition of python on windows. Had some issues getting the packages installed and running at first until I switched over.

**Comment by N-Bz** [comment]
Since @hsy77101 did not post here since 11 days, I'll assume that @Tala (btw, thanks for this !) answers solved his problem.

**Comment by hsy77101** [comment]
Sorry. I was on business trip.
I am still on looking for the solution.

**Comment by Tala** [comment]
I mainly use Anaconda python x64 and didn't have any problems installing the packages. If you have further information what are the problems @hsy77101 please let us know.

**Comment by ayste** [comment]
i have the same problem but in kali linux 
( File "brutespray.py", line 4, in <module>
    import readline, glob
ImportError: No module named readline)
plz someone can help

**Comment by naveenshankar61** [comment]
I am facing this issue in my Sles-10 machine with 2.7.10 python version

[20180719-05:19:09|root@hgtest01-vm04 ~] python
Python 2.7.10 (default, Jul 18 2018, 01:02:37)
[GCC 4.1.2 20070115 (SUSE Linux)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "/etc/pythonstart", line 7, in <module>
    import readline
ImportError: No module named readline
>>>

Please help.

**Comment by justwannahelp** [comment]
SLES 11 SP4
I had the same problem and was able to fix it by installing  libreadline5-32bit.

hostname: # python2
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "/etc/pythonstart", line 7, in <module>
    import readline
ImportError: No module named readline


hostname:  # zypper in libreadline5-32bit

hostname: # python2
Python 2.6.9 (unknown, Apr  7 2015, 08:28:12)
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by amaljose01** [comment]
installlocation\lib\site-packages\vault\modules\autocomplete.py", line 2, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

you need to install pyreadline if you are using windows from CLI
pip install pyreadline
Collecting pyreadline
  Downloading https://files.pythonhosted.org/packages/bc/7c/d724ef1ec3ab2125f38a1d53285745445ec4a8f19b9bb0761b4064316679/pyreadline-2.1.zip (109kB)
     |████████████████████████████████| 112kB 113kB/s
Installing collected packages: pyreadline
  Running setup.py install for pyreadline ... done
Successfully installed pyreadline-2.1

vault
    __      __         _ _           .----.
    \ \    / /        | | |         / /  \ \
     \ \  / /_ _ _   _| | |_       _| |__| |_
      \ \/ / _` | | | | | __|    .' |_   |_| '.
       \  / (_| | |_| | | |_     '.__________.'
        \/ \__,_|\__,_|_|\__|    |            |
                                 '.__________.'
Welcome to Vault. Please choose a secure secret key.

**Comment by Sah7134** [comment]
just install readline with:
pip install readline

KR ;)
