### ISSUE TITLE
Couldn't find your e-mail

### ISSUE THREAD

**Issue by ramonsaraiva** [N-Bz/bybop#7]
Hello, sorry for creating an issue for this, but i couldn't find your e-mail to ask you through there..

I just bought a Parrot Bebop 2, but i have no idea how their SDK works. Is this code also compatible with Bebop 2? If so, i will probably be contributing to this a lot, cause i want to play around with that drone and Python.

Thanks,
Ramon.

**Comment by N-Bz** [comment]
Hi,

Yes, this repo si compatible with the Bebop 2. I try to keep it up to date with the official SDK.
Anyway, please note that bybop "alone" is not sufficient for proper piloting of the drone (see my comments to this [pull request](https://github.com/N-Bz/bybop/pull/6), specially about the PCMD loop), and you'll have to create an "upper layer" on top of it if you want to do more thanthe basic "sending & receiving commands" stuff this was designed for.

And about the official SDK (which includes all the commands used by this implementation), the best place to ask is the [official developer forum](http://forum.developer.parrot.com/).

Nicolas.

**Comment by ramonsaraiva** [comment]
Understood.

Do you have any samples you've created that actually send commands using this library and make the drone react to it? Could you share it if you do?
