### ISSUE TITLE
How to use PCMD command in Piloting

### ISSUE THREAD

**Issue by cyleong84** [N-Bz/bybop#8]
I wish to use PMCD command to move the Bebop2 to a relative point from current position.
I have tried:
>> drone.send_data('ardrone3.Piloting.PCMD( 1, 1, 0, 0 , 0 )') 
but I got error:
Bad command !'Unknown command PCMD( 1, 1, 0, 0 , 0 ) in class Piloting of project ardrone3'
1

**Comment by N-Bz** [comment]
`help(Bybop_Device.Device.send_data)` should give you the answer.
